import type { Laptop, AIDeal, AgentState } from "@/types/laptop";

export const MOCK_LAPTOPS: Laptop[] = [
  {
    id: "nb_001",
    brand: "ASUS",
    model: "ROG Zephyrus G14 (2024)",
    slug: "asus-rog-zephyrus-g14-2024",
    price: 1899.99,
    original_price: 2399.99,
    discount_pct: 21,
    ai_score: 94,
    ai_score_label: "ÓPTIMO",
    price_trend: "down",
    cpu: "AMD Ryzen 9 8945HS",
    ram_gb: 32,
    storage_gb: 1000,
    gpu: "RTX 4070 8GB",
    display_inches: 14,
    battery_wh: 73,
    weight_kg: 1.65,
    category: "gaming",
    retailer: "Amazon",
    affiliate_url: "#",
    image_url: "",
    detected_at: "2024-12-14T18:30:00Z",
    is_featured_deal: true,
    in_stock: true,
  },
  {
    id: "nb_002",
    brand: "Dell",
    model: "XPS 15 9530",
    slug: "dell-xps-15-9530",
    price: 1349.0,
    original_price: 1599.0,
    discount_pct: 16,
    ai_score: 88,
    ai_score_label: "BUENO",
    price_trend: "stable",
    cpu: "Intel Core i7-13700H",
    ram_gb: 16,
    storage_gb: 512,
    gpu: "RTX 4050 6GB",
    display_inches: 15.6,
    battery_wh: 86,
    weight_kg: 1.86,
    category: "creator",
    retailer: "Dell",
    affiliate_url: "#",
    image_url: "",
    detected_at: "2024-12-14T17:00:00Z",
    is_featured_deal: false,
    in_stock: true,
  },
  {
    id: "nb_003",
    brand: "Lenovo",
    model: "ThinkPad X1 Carbon Gen 12",
    slug: "lenovo-thinkpad-x1-carbon-gen-12",
    price: 1189.0,
    original_price: 1549.0,
    discount_pct: 23,
    ai_score: 91,
    ai_score_label: "ÓPTIMO",
    price_trend: "down",
    cpu: "Intel Core Ultra 7 165U",
    ram_gb: 32,
    storage_gb: 1000,
    gpu: "Intel Arc Graphics",
    display_inches: 14,
    battery_wh: 57,
    weight_kg: 1.12,
    category: "business",
    retailer: "Lenovo",
    affiliate_url: "#",
    image_url: "",
    detected_at: "2024-12-14T16:45:00Z",
    is_featured_deal: true,
    in_stock: true,
  },
  {
    id: "nb_004",
    brand: "HP",
    model: "Spectre x360 14",
    slug: "hp-spectre-x360-14",
    price: 979.0,
    original_price: 1199.0,
    discount_pct: 18,
    ai_score: 82,
    ai_score_label: "BUENO",
    price_trend: "down",
    cpu: "Intel Core Ultra 5 125H",
    ram_gb: 16,
    storage_gb: 512,
    gpu: "Intel Arc Graphics",
    display_inches: 14,
    battery_wh: 68,
    weight_kg: 1.45,
    category: "ultrabook",
    retailer: "HP",
    affiliate_url: "#",
    image_url: "",
    detected_at: "2024-12-14T15:20:00Z",
    is_featured_deal: false,
    in_stock: true,
  },
  {
    id: "nb_005",
    brand: "Apple",
    model: "MacBook Pro 14\" M3 Pro",
    slug: "apple-macbook-pro-14-m3-pro",
    price: 1799.0,
    original_price: 1999.0,
    discount_pct: 10,
    ai_score: 96,
    ai_score_label: "ÓPTIMO",
    price_trend: "stable",
    cpu: "Apple M3 Pro 12-core",
    ram_gb: 18,
    storage_gb: 512,
    gpu: "Apple M3 Pro 18-core GPU",
    display_inches: 14.2,
    battery_wh: 72.4,
    weight_kg: 1.61,
    category: "workstation",
    retailer: "Amazon",
    affiliate_url: "#",
    image_url: "",
    detected_at: "2024-12-14T14:00:00Z",
    is_featured_deal: false,
    in_stock: true,
  },
  {
    id: "nb_006",
    brand: "Acer",
    model: "Swift X 14",
    slug: "acer-swift-x-14",
    price: 699.0,
    original_price: 899.0,
    discount_pct: 22,
    ai_score: 75,
    ai_score_label: "BUENO",
    price_trend: "down",
    cpu: "AMD Ryzen 7 7745HX",
    ram_gb: 16,
    storage_gb: 512,
    gpu: "RTX 4050 6GB",
    display_inches: 14.5,
    battery_wh: 65,
    weight_kg: 1.47,
    category: "budget",
    retailer: "Amazon",
    affiliate_url: "#",
    image_url: "",
    detected_at: "2024-12-14T12:30:00Z",
    is_featured_deal: false,
    in_stock: false,
  }
];

export const MOCK_AI_DEALS: AIDeal[] = [
  {
    laptop_id: "nb_001",
    headline: "Precio mínimo histórico - ROG Zephyrus G14",
    savings: 300.0,
    confidence: 0.97,
    expires_at: "2024-12-15T23:59:59Z",
  },
  {
    laptop_id: "nb_003",
    headline: "Caída del 23% detectada - ThinkPad X1 Carbon",
    savings: 360.0,
    confidence: 0.91,
    expires_at: null,
  },
  {
    laptop_id: "nb_006",
    headline: "Flash sale Amazon - Acer Swift X 14",
    savings: 200.0,
    confidence: 0.83,
    expires_at: "2024-12-14T20:00:00Z",
  }
];

export const MOCK_AGENT_STATE: AgentState = {
  status: "scanning",
  last_run: "2024-12-14T18:28:00Z",
  deals_found: 14,
  sources_checked: 7,
};
